maxRareCrafts: 1

tokens:
  UNKNOWN:
    cooldown: 1
  FIRE:
    cooldown: 90

    # Active
    strength: 2.65
    speed: 2.0
  WARDEN:
    cooldown: 240
    maxCrafts: 3

    # Passive
    chance: 0.05
    duration: 7

    # Active
    radius: 15
    activeDuration: 15
  SMELTER:
    cooldown: 210

    # Passive
    appliesTo:
      - "WOODEN_PICKAXE"
      - "COPPER_PICKAXE"
      - "IRON_PICKAXE"
      - "GOLD_PICKAXE"
      - "DIAMOND_PICKAXE"
      - "NETHERITE_PICKAXE"

      - "WOODEN_SHOVEL"
      - "COPPER_SHOVEL"
      - "IRON_SHOVEL"
      - "GOLD_SHOVEL"
      - "DIAMOND_SHOVEL"
      - "NETHERITE_SHOVEL"

      - "WOODEN_AXE"
      - "COPPER_AXE"
      - "IRON_AXE"
      - "GOLD_AXE"
      - "DIAMOND_AXE"
      - "NETHERITE_AXE"

    # Active
    duration: 20
  AIR:
    cooldown: 15

    # Active
    multiplier: 1
    lift: 0.5
  CRAB:
    cooldown: 1
    maxCrafts: 3

    # Passive
    rangeMultiplier: 0.7
    appliesTo:
      - "SHEARS"

      - "WOODEN_PICKAXE"
      - "COPPER_PICKAXE"
      - "IRON_PICKAXE"
      - "GOLD_PICKAXE"
      - "DIAMOND_PICKAXE"
      - "NETHERITE_PICKAXE"

      - "WOODEN_HOE"
      - "COPPER_HOE"
      - "IRON_HOE"
      - "GOLD_HOE"
      - "DIAMOND_HOE"
      - "NETHERITE_HOE"

      - "WOODEN_SWORD"
      - "COPPER_SWORD"
      - "IRON_SWORD"
      - "GOLD_SWORD"
      - "DIAMOND_SWORD"
      - "NETHERITE_SWORD"

      - "WOODEN_SHOVEL"
      - "COPPER_SHOVEL"
      - "IRON_SHOVEL"
      - "GOLD_SHOVEL"
      - "DIAMOND_SHOVEL"
      - "NETHERITE_SHOVEL"

      - "WOODEN_AXE"
      - "COPPER_AXE"
      - "IRON_AXE"
      - "GOLD_AXE"
      - "DIAMOND_AXE"
      - "NETHERITE_AXE"
  POTION:
    cooldown: 300

    # Active
    multiplier: 1.5
  VILLAGER:
    cooldown: 1

    # Passive
  HEART:
    cooldown: 240

    # Passive
    heartMod: 10

    # Active
    resistanceTime: 30
    resistanceAmplifier: 2

trader:
  min: 60
  max: 240
  kill: 15

events:
  NONE:
  BOUNTY:
    # Multipliers to the base value. All those values add up to the final bounty multiplied by the random range
    bountyMultipliers:
      # Hours of playtime
      playtimeHours: 1.5
      # Armor (counted once per piece)
      # None, Other,  Leather,  Copper, Chainmail,  Iron, Gold, Diamond,  Netherite
      # -4    4       2         2       2           6     4     10        12
      armor: 5
      # Amount of kills
      kills: 2.5
      # Amount of deaths
      deaths: -0.1
      # Amount of coins currently posessed.
      coins: 0.35

      # Random multiplier
      minRand: 0.8
      maxRand: 1.25

    # The killed/popped player gets a reduction of bounty * multiplier
    killedReductionMultiplier: 0.5

titles:
  traderSpawned: "<light_blue>A Wandering Trader has appeared!"
subtitles:
  traderSpawned: "Find him at /spawn"
